version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: sh -c "cd app/ && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/ecommerce/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/${domain}/privkey.pem:/etc/letsencrypt/live/${domain}/privkey.pem
      - /etc/letsencrypt/live/${domain}/fullchain.pem:/etc/letsencrypt/live/${domain}/fullchain.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
  

volumes:
  postgres_data:
