version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app/:/home/azure/ecommerce/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web  

volumes:
  postgres_data:
