# Generated by Django 4.0.2 on 2022-02-18 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_userdetail_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
