# Generated by Django 4.0.2 on 2022-02-18 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userdetail_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
