# Generated by Django 4.0.2 on 2022-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_userorders_quantity_userorders_orderdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemimg',
            field=models.ImageField(default='item_images/default.png', upload_to='item_images'),
        ),
    ]
